name: Django CI/CD with Docker

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build . -t myproject

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: mhd0012
        password: asrmhd.001225

    - name: Push Docker image to Docker Hub
      run: docker push myproject
